export const BLOGS = {
  GET_BLOGS: "GET_BLOGS",
  GET_BLOG: "GET_BLOG",
  DELETE_BLOG: "DELETE_BLOG",
  CREATE_BLOG: "CREATE_BLOG",
  EDIT_BLOG: "EDIT_BLOG"
}

export const USERS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOG_CHECK: "LOG_CHECK",
  REGISTER: "REGISTER"
}